// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitiaDuty.Data;

#nullable disable

namespace MilitiaDuty.Migrations
{
    [DbContext(typeof(MilitiaContext))]
    partial class MilitiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("MilitiaDuty.Models.DutyDates.DutyDate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFullDutyDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DutyDates");
                });

            modelBuilder.Entity("MilitiaDuty.Models.DutyDates.MilitiaDutyDate", b =>
                {
                    b.Property<uint>("MilitiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DutyDateId")
                        .HasColumnType("TEXT");

                    b.HasKey("MilitiaId", "DutyDateId");

                    b.HasIndex("DutyDateId");

                    b.ToTable("MilitiaDutyDates");
                });

            modelBuilder.Entity("MilitiaDuty.Models.Militias.Militia", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Militias");
                });

            modelBuilder.Entity("MilitiaDuty.Models.DutyDates.MilitiaDutyDate", b =>
                {
                    b.HasOne("MilitiaDuty.Models.DutyDates.DutyDate", null)
                        .WithMany()
                        .HasForeignKey("DutyDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilitiaDuty.Models.Militias.Militia", null)
                        .WithMany()
                        .HasForeignKey("MilitiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
